name: Amicus
favicon: null
layout_spectrum: 0.14601
typography_spectrum: 0.49643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152d2b'
    - '#c0cddf'
    - '#6e9bc1'
    - '#007fb0'
    - '#6d5f56'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
