name: Amicus
favicon: null
layout_spectrum: 0.6651055689435452
typography_spectrum: 0.9391776842530817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2956124092452228
  lightness: 0.08000441989861429
  saturation: 0.514349301578477
  rhythmicContrast: 0.6310191371012479
purpose: []
